#!/bin/bash
# lib/modulefile.sh — Lmod .lua module file generator

# generate_module <libname> <version> <prefix> <compiler> <cversion> <module_root>
#                 [ucx_root] [ucc_root] [hcoll_root]
generate_module() {
    local libname="$1"
    local version="$2"
    local prefix="${3%/}"
    local compiler="$4"
    local cversion="$5"
    local module_root="${6%/}"
    local ucx_root="${7:-}"
    local ucc_root="${8:-}"
    local hcoll_root="${9:-}"

    local moduledir="${module_root}/${libname}/${version}/${compiler}"
    local modulefile="${moduledir}/${cversion}.lua"

    mkdir -p "$moduledir"

    # ---- Header ----
    cat >"$modulefile" <<EOF
-- -*- lua -*-
-- Module for ${libname^^} ${version}
-- Generated by build_mpi_stack.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
whatis("Name: ${libname^^}")
whatis("Version: ${version}")
whatis("Category: MPI/SciLib")
whatis("Description: ${libname^^} ${version} built with ${compiler^^} ${cversion}")

local root = "${prefix}"
setenv("${libname^^}_ROOT", root)
EOF

    # ---- Optional dependency roots ----
    if [[ "$libname" == "openmpi" ]]; then
        [[ -n "$ucx_root" ]] && cat >>"$modulefile" <<EOF

local ucx_root = "${ucx_root}"
setenv("UCX_ROOT", ucx_root)
EOF
        [[ -n "$ucc_root" ]] && cat >>"$modulefile" <<EOF

local ucc_root = "${ucc_root}"
setenv("UCC_ROOT", ucc_root)
EOF
        [[ -n "$hcoll_root" ]] && cat >>"$modulefile" <<EOF

local hcoll_root = "${hcoll_root}"
setenv("HCOLL_ROOT", hcoll_root)
EOF
    fi

    # ---- Conflict declarations (openmpi only) ----
    if [[ "$libname" == "openmpi" ]]; then
        cat >>"$modulefile" <<'LUAEOF'

-- Prevent loading alongside other MPI implementations
conflict("openmpi")
conflict("intelmpi")
conflict("intel-mpi")
conflict("mpich")
conflict("mvapich")
conflict("mvapich2")
LUAEOF
    fi

    # ---- Compiler prerequisite ----
    cat >>"$modulefile" <<EOF

-- Require compiler module
if not isloaded("${compiler}/${cversion}") then
    load("${compiler}/${cversion}")
end

-- Paths for this package
prepend_path("PATH",             pathJoin(root, "bin"))
prepend_path("LD_LIBRARY_PATH",  pathJoin(root, "lib"))
prepend_path("LD_LIBRARY_PATH",  pathJoin(root, "lib64"))
prepend_path("LIBRARY_PATH",     pathJoin(root, "lib"))
prepend_path("LIBRARY_PATH",     pathJoin(root, "lib64"))
prepend_path("C_INCLUDE_PATH",   pathJoin(root, "include"))
prepend_path("CPLUS_INCLUDE_PATH", pathJoin(root, "include"))
prepend_path("PKG_CONFIG_PATH",  pathJoin(root, "lib/pkgconfig"))
EOF

    # ---- Dependency paths (only for openmpi module) ----
    if [[ "$libname" == "openmpi" ]]; then
        for dep_root in "$ucx_root" "$ucc_root" "$hcoll_root"; do
            [[ -z "$dep_root" ]] && continue
            cat >>"$modulefile" <<EOF

-- Dependency: ${dep_root}
prepend_path("PATH",             pathJoin("${dep_root}", "bin"))
prepend_path("LD_LIBRARY_PATH",  pathJoin("${dep_root}", "lib"))
prepend_path("LD_LIBRARY_PATH",  pathJoin("${dep_root}", "lib64"))
prepend_path("LIBRARY_PATH",     pathJoin("${dep_root}", "lib"))
prepend_path("C_INCLUDE_PATH",   pathJoin("${dep_root}", "include"))
prepend_path("CPLUS_INCLUDE_PATH", pathJoin("${dep_root}", "include"))
prepend_path("PKG_CONFIG_PATH",  pathJoin("${dep_root}", "lib/pkgconfig"))
EOF
        done
    fi

    # ---- OpenMPI runtime guards ----
    if [[ "$libname" == "openmpi" ]]; then
        cat >>"$modulefile" <<'LUAEOF'

-- Pin MCA plugin search to this install only.
-- Prevents accidental loading of system hcoll or other incompatible plugins
-- from /opt/mellanox or other HPC-X paths on the node.
setenv("OMPI_MCA_mca_base_component_path", pathJoin(root, "lib/openmpi"))

-- Suppress UCX_ROOT "unused variable" warning (it is a build convenience
-- variable, not a UCX runtime variable).
setenv("UCX_WARN_UNUSED_ENV_VARS", "n")
LUAEOF
    fi

    log_ok "Module: ${modulefile}"
}
